- hosts: localhost, localhost2
  gather_facts: no
  tasks:
  - name: ping module
    ping:
    register: ping_result

  - name: run command
    command: whoami
    register: cmd_res

  - debug:
      var: cmd_res

- import_playbook: sub.yml

- name: play 2
  hosts: localhost
  tasks:
  - ping: